dist: xenial
language: c

addons:
  apt:
    packages:
    - git
    - git-core
    - gnupg
    - flex
    - bison
    - gperf
    - build-essential
    - zip
    - curl
    - zlib1g-dev
    - gcc-multilib
    - g++-multilib
    - libc6-dev-i386
    - lib32ncurses5-dev
    - x11proto-core-dev
    - libx11-dev
    - lib32z-dev
    - ccache
    - libgl1-mesa-dev
    - libxml2-utils
    - xsltproc
    - unzip
    - maven
    - schedtool

cache: ccache

env:
    global:
        - LC_ALL=C
        - USE_CCACHE=true
        - ALLOW_MISSING_DEPENDENCIES=true

before_install:
    - git config --global color.ui false
    - sudo bash -c "curl https://storage.googleapis.com/git-repo-downloads/repo > /bin/repo && chmod a+x /bin/repo"
    - mkdir -p $HOME/sources && cd $HOME/sources
    - repo init --depth=1 -u git://github.com/omnirom/android.git -b android-9.0
    - repo sync
    - mkdir -p device/xiaomi
    - cp -r $TRAVIS_BUILD_DIR device/xiaomi/lavender

script:
    - source build/envsetup.sh && lunch omni_lavender-eng && mka recoveryimage

before_deploy:
    - export FILE_TO_UPLOAD=$HOME/sources/out/target/product/lavender/recovery.img

deploy:
    provider: releases
    api_key: $OAUTH_KEY
    file: $FILE_TO_UPLOAD
    skip_cleanup: true
    on:
        tags: true 
